name: cca-project-action
description: Track the usage of claude-code-action in a GitHub project
inputs:
  execution-file:
    description: Path to the execution file from claude-code-action
    required: false
  project-id:
    description: GitHub project ID
    required: true
  project-field-id-last-called-at:
    description: GitHub project field ID for the last called date
    required: false
  project-field-id-calls:
    description: GitHub project field ID for the cumulative calls
    required: false
  project-field-id-cost-usd:
    description: GitHub project field ID for the cumulative cost in USD
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
outputs:
  cumulative-calls:
    description: Cumulative number of calls to claude-code-action
  cumulative-cost-usd:
    description: Cumulative cost in USD of claude-code-action
runs:
  using: 'node20'
  main: 'dist/index.js'
